FROM ubuntu:latest

# docker build -t ubuntu-one .
# docker run ubuntu-one  // only last command (CMD) was shown
RUN apt-get -y update && apt-get install -y python

#CMD bash --version
#CMD cat /etc/debian_version
CMD python --version

