/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_th_aae_MyActivity */

#ifndef _Included_co_th_aae_MyActivity
#define _Included_co_th_aae_MyActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_th_aae_MyActivity
 * Method:    getMyData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_co_th_aae_MyActivity_getMyData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
