# recommended
# FROM node:4-onbuild

# trusty 0.10.25
FROM node:0.10-onbuild

VOLUME /usr/src/app

RUN npm install
RUN npm install -g nodemon

# replace this with your application's default port
EXPOSE 3001
