# Example configuration file (e.g. /etc/nginx/sites-available/stopwatch.conf)
server {
    listen 80;
    listen [::]:80;

    server_name stopwatch.com;

    root /var/www/stopwatch;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
